name: Deploy BFF Donaton

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/donatonback/api-bff:latest"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy-public:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Desplegar bff en ec2 publica
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/donatonback/api-bff:latest"
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_PUBLIC_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Desplegando BFF en Puerto 4000" \
            --parameters "{\"commands\":[
              \"set -e\",
              \"aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}\",
              \"sudo docker pull $IMAGE_URI\",
              \"sudo docker stop bff-node || true\",
              \"sudo docker rm bff-node || true\",
              \"sudo docker run -d --name bff-node -p 4000:4000 -e GATEWAY_URL=http://${{ secrets.GATEWAY_PRIVATE_IP }}:8086 $IMAGE_URI\",
              \"sudo docker image prune -f\"
            ]}"
